-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

select * from gcp_mysql_fc1.practice2.shipments

-- COMMAND ----------

SELECT * FROM etl_practice.etl_data.shipment1_bronze1

-- COMMAND ----------

SELECT * FROM lakehousecat.deltadb.drugstb1 where uniqueid in (70362,103669)

-- COMMAND ----------

--select * from lakehousecat.deltadb.drugstbl
--5,690 rows
insert into lakehousecat.deltadb.drugstb1(uniqueid,drugname,rating) values(10000013,'abc',10);
update lakehousecat.deltadb.drugstb1 set drugname='xyzz' where uniqueid=70362;

-- COMMAND ----------

SELECT * FROM lakehousecat.deltadb.drugstb1 where uniqueid in (70362,103669,10000013)

-- COMMAND ----------

insert into lakehousecat.deltadb.drugstb1(uniqueid,drugname,rating) values(143,'abc',10);

-- COMMAND ----------

SELECT * FROM etl_practice.etl_data.drugs_stream_bronze_table1 where uniqueid=143
